config/routes.rb
Rails.application.routes.draw do

  get 'clients/new'

  resources :users
  resources :sessions, only: [:new, :create, :destroy] 
  resources :clients
  resources :issues

  root to: 'static_pages#home', :via => :get
  
  match '/signup' => 'users#new', :via => :get, :as => 'signup'
  match '/signin' => 'sessions#new', :via => :get, :as => 'signin'
  match '/signout' => 'sessions#destroy', :via => :delete
  match '/help' => 'static_pages#help', :via => :get, :as => 'help'
  match '/about' => 'static_pages#about', :via => :get, :as => 'about'
  match '/contact' => 'static_pages#contact', :via => :get, :as => 'contact'

end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Client < ActiveRecord::Base

	validates :name, presence: true, length: { maximum: 50 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  team            :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base

	has_secure_password

	before_save { |user| user.email = email.downcase }

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
  									format: { with: VALID_EMAIL_REGEX },
  									uniqueness: { case_sensitive:false }
	validates :team, presence: true
	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  
  def show
		@client = Client.find(params[:id])
	end

  def new
  end

  def index
  	@clients = Client.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to clients_path
		else
			flash.now[:error] = 'Invalid email/password combination' # Not quite right!
			render 'new'
		end	
	end

	def destroy
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  	@user = User.new
  end

  def create
		@user = User.new(user_params)
		if @user.save
			redirect_to clients_path
		else
			render 'new'
		end
	end

	private

  def user_params
    params.require(:user).permit(:name, :email, :team, :password, :password_confirmation)
  end

  def signin
  end



end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis
	def full_title(page_title)
		base_title = "Issue Tracker"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
	
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/index.html.erb
<% provide(:title, 'All clients') %>
<h1>All clients</h1>

<ul class="clients">
	<% @clients.each do |client| %>
		<li>
			<%= link_to client.name, client %>
		</li>
	<% end %>
</ul>

app/views/clients/new.html.erb
<h1>Clients#new</h1>
<p>Find me in app/views/clients/new.html.erb</p>

app/views/clients/show.html.erb
<% provide(:title, 'Clients') %>
<h1><%= @client.name %></h1>

<h2>
	List of issues
</h2>

app/views/layouts/_footer.erb
<footer class="footer">
	<small>
		<%= link_to "Issue Tracker", root_path %>
		by Jozef Figur
	</small>
	<nav>
		<ul>
			<li><a href="http://www.etops.ch">Etops</a></li>
			<li><a href="http://www.fundbase.com">Fundbase</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "issue tracker", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<li><%= link_to "Sign in", signin_path %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title><%= full_title(yield(:title)) %></title>
  	<%= stylesheet_link_tag 'application', media: 'all' %>
  	<%= javascript_include_tag 'application' %>
  	<%= csrf_meta_tags %>
  	<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>	
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
	The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
	is a project to make a book and screencasts to teach web development
	with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
	is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	Contact Ruby on Rails Tutorial about the sample app at the
	<a href="http://railstutorial.org/contact">contact page</a>.
</p>		

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
	Get help on the Issue Tracker application on this site.
</p>

app/views/static_pages/home.html.erb
<div class="center">
	<h1>Welcome to the Issue Tracker Web Application</h1>
	
	<h2>
		Issue Tracker helps to track issues related to Etops and Fundbase services
	</h2>

	<%= link_to "Sign up", signup_path, class: "btn btn-primary" %>
	<%= link_to "Sign in", signin_path %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
		
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :team %>
			<%= f.text_field :team %>			
		
			<%= f.label :password %>
			<%= f.password_field :password %>
		
			<%= f.label :password_confirmation, "Password Confirmation" %>
			<%= f.password_field :password_confirmation %>

			<br><br>
		
			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>